sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an Image with dockerfile"
  - docker build -t chigony/react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true chigony/react-app npm run test -- --coverage

after_success:
  - echo "Test Success"

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app"
  env: "DockerReactApp-env-1"
  bucket_name: "elasticbeanstalk-ap-northeast-2-669098787767"
  bucket_path: "docker-react-app"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY